In [1]:
from MyNeural import Neural
import numpy as np
from MyNeural import MyLoss

In [2]:

neuron = Neural(loss=MyLoss.MSE_loss)

neuron.add(neurons=3, activation='linear')
neuron.add(neurons=6, activation="relu")
neuron.add(neurons=9, activation="relu")
neuron.add(neurons=1, activation="linear")
# X = np.array([[2], [2], [1], [2], [2], [1]])
# y = np.array([[1, 1, 0, 1, 1, 0]])

X = np.random.randint(low=1, high=3, size=(300,3))

# Generate random output data       
y = np.random.randint(low=0, high=2, size=(1,300))

neuron.fit(X, y, learning_rate=0.0001)
neuron.save_model("salom.json")
# print(neuron.biases)
print(neuron.predict(X[:10]))

Epoch: 900  loss: 0.3632574236043568

<class 'function'>
[[0.19942595]
 [0.3325254 ]
 [0.21681075]
 [0.19942595]
 [0.3325254 ]
 [0.19942595]
 [0.23416932]
 [0.31516683]
 [0.29778203]
 [0.15824837]]


In [2]:
neuron = Neural(loss=MyLoss.MSE_loss)

In [5]:
neuron = neuron.load_model(model_path="salom.json")

In [6]:
neuron.weights

[array([[-0.41741707, -0.62460943,  0.07439609, -0.57241597,  0.13113485,
         -0.07326577],
        [-0.73713987, -0.81216385, -0.38840732, -0.39157583, -0.13133305,
         -0.54319063],
        [-0.36547625,  0.13705158, -0.92733234,  0.53359837,  0.74302832,
         -0.71883666]]),
 array([[-0.44259977,  0.34431246, -0.28105042,  0.49703788, -0.48898821,
         -0.2800719 ,  0.84489069,  0.11508767, -0.05828665],
        [ 0.31758845, -0.39257344, -0.2828227 ,  0.38003059,  0.33799716,
          0.3328967 , -0.66328495, -0.28778882, -0.69044327],
        [ 0.77780189, -0.17738547, -0.02677625,  0.54204779, -0.91188333,
         -0.00489485,  0.3170179 ,  0.71497224, -0.3554082 ],
        [ 0.51418371, -0.97848841,  0.93385025, -0.41920062,  0.74130549,
          0.09399229,  0.63569707,  0.83758098, -0.80851209],
        [-0.15764838, -0.05835378, -0.20599625, -0.57704501, -0.69340457,
          0.89709922,  0.47271026,  0.2296257 , -0.38960471],
        [-0.85920554,  0.31

In [4]:
neuron.weights[2].shape

(9, 1)

In [5]:
import random
col1 = []
col2 = []
col3 = []
col4 = []
col5 = []
label = []

for i in range(300):
    col1.append(random.uniform(0, 1))
    col2.append(random.uniform(0, 1))
    col3.append(random.uniform(0, 1))
    col4.append(random.uniform(0, 1))
    col5.append(random.uniform(0, 1))
    label.append(random.choice([0, 1]))

In [6]:
dataset = np.array([np.array(col1),np.array(col2),np.array(col3),np.array(col4),np.array(col5)])
label = np.array([np.array(label)])

In [7]:
neuron2 = Neural()
neuron2.add(neurons=5, activation='linear')
neuron2.add(neurons=3, activation="relu")
neuron2.add(neurons=3, activation="relu")
neuron2.add(neurons=1, activation="linear")

In [8]:
neuron2.fit(X = dataset.T, y=label, learning_rate=0.001)

Epoch: 900  loss: 0.25316094524412773



In [9]:
neuron2.save_model(model_path="random_model")

<class 'function'>


In [10]:
neuron2.predict(X = dataset.T)

array([[0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.39599258],
       [0.395