In [1]:
from MyNeural import Neural
import numpy as np
from MyNeural import MyLoss

In [2]:

neuron = Neural(loss=MyLoss.MSE_loss)

neuron.add(neurons=3, activation='linear')
neuron.add(neurons=6, activation="relu")
neuron.add(neurons=9, activation="relu")
neuron.add(neurons=1, activation="linear")
# X = np.array([[2], [2], [1], [2], [2], [1]])
# y = np.array([[1, 1, 0, 1, 1, 0]])

X = np.random.randint(low=1, high=3, size=(300,3))

# Generate random output data       
y = np.random.randint(low=0, high=2, size=(1,300))

neuron.fit(X, y, epochs = 1520, learning_rate=0.0001)
neuron.save_model("salom.json")
# print(neuron.biases)
print(neuron.predict(X[:10]))

Epoch: 151  loss: 0.23058785953330082
Epoch: 303  loss: 0.22908165518055123
Epoch: 455  loss: 0.22990320361306837
Epoch: 607  loss: 0.23090565802802887
Epoch: 759  loss: 0.23198156208347423
Epoch: 911  loss: 0.23308576124292585
Epoch: 1063  loss: 0.23419308822026018
Epoch: 1215  loss: 0.23529204945505613
Epoch: 1367  loss: 0.23637858078818977
Epoch: 1519  loss: 0.23745258317560222<class 'function'>
[[0.38461432]
 [0.38461432]
 [0.42398862]
 [0.53542209]
 [0.62777883]
 [0.62777883]
 [0.38461432]
 [0.46363602]
 [0.50546856]
 [0.30912494]]


In [3]:
neuron = Neural(loss=MyLoss.MSE_loss)

In [4]:
neuron = neuron.load_model(model_path="salom.json")

In [5]:
neuron.weights

[array([[ 0.12929717,  0.51648175,  0.67604235,  0.94948008,  0.04159642,
          0.1127903 ],
        [-0.27929527,  0.06652942,  0.24165667,  0.75243689, -0.27044109,
          0.1571489 ],
        [ 0.06161725,  0.44544949, -0.98968636,  0.67072633,  0.53807213,
         -0.49352957]]),
 array([[-0.12589581, -0.83506069, -0.35194342, -0.35012219,  0.05316504,
         -0.22852808, -0.54086803,  0.2243765 ,  0.59854227],
        [ 0.35738193,  0.03533039,  0.95612979, -0.0549001 ,  0.61531933,
          0.31462085,  0.13324229, -0.25140404,  0.17871372],
        [ 0.46554727, -0.88533282,  0.43052835, -0.04182456,  0.00603846,
          1.03848065,  0.80841412,  0.90881874, -0.4812665 ],
        [-0.06230827, -0.27606979,  0.89434076,  0.25376073, -0.01195928,
         -0.41620491, -0.25216945,  0.75105079, -0.2493467 ],
        [ 0.40308321,  0.61347   , -0.22200191, -0.26659104, -0.51285362,
          0.76495563,  0.00673668, -0.3301887 , -0.61667041],
        [-0.17503954, -0.52

In [6]:
neuron.weights[2].shape

(9, 1)

In [7]:
import random
col1 = []
col2 = []
col3 = []
col4 = []
col5 = []
label = []

for i in range(300):
    col1.append(random.uniform(0, 1))
    col2.append(random.uniform(0, 1))
    col3.append(random.uniform(0, 1))
    col4.append(random.uniform(0, 1))
    col5.append(random.uniform(0, 1))
    label.append(random.choice([0, 1]))

In [8]:
dataset = np.array([np.array(col1),np.array(col2),np.array(col3),np.array(col4),np.array(col5)])
label = np.array([np.array(label)])

In [9]:
neuron2 = Neural()
neuron2.add(neurons=5, activation='linear')
neuron2.add(neurons=3, activation="relu")
neuron2.add(neurons=3, activation="relu")
neuron2.add(neurons=1, activation="linear")

In [10]:
neuron2.fit(X = dataset.T, y=label, learning_rate=0.001)

Epoch: 99  loss: 0.29981274921347806
Epoch: 199  loss: 0.27238668579009336
Epoch: 299  loss: 0.26133219453503657
Epoch: 399  loss: 0.25643281085736843
Epoch: 499  loss: 0.25428356977755556
Epoch: 599  loss: 0.25275988850918724
Epoch: 699  loss: 0.25042075310140897
Epoch: 799  loss: 0.24887916133762778
Epoch: 899  loss: 0.24870671894805443
Epoch: 999  loss: 0.24864846931808335

In [11]:
neuron2.save_model(model_path="random_model")

<class 'function'>


In [12]:
neuron2.predict(X = dataset.T)

array([[0.50347644],
       [0.50473424],
       [0.48826964],
       [0.52485281],
       [0.55148517],
       [0.51557942],
       [0.50712072],
       [0.54332748],
       [0.50469456],
       [0.50363521],
       [0.49523142],
       [0.56778771],
       [0.52013097],
       [0.56451381],
       [0.53379494],
       [0.53469236],
       [0.50377488],
       [0.594544  ],
       [0.51192855],
       [0.55314292],
       [0.47470511],
       [0.51349419],
       [0.4843591 ],
       [0.50027285],
       [0.53672073],
       [0.56069599],
       [0.55406955],
       [0.56761466],
       [0.51071585],
       [0.53391659],
       [0.51743878],
       [0.50426329],
       [0.51329731],
       [0.55153989],
       [0.5032865 ],
       [0.55973291],
       [0.55185978],
       [0.52085483],
       [0.50941371],
       [0.76334082],
       [0.53227526],
       [0.49025411],
       [0.49590233],
       [0.53165386],
       [0.52215987],
       [0.50137086],
       [0.51742639],
       [0.575